version: '3.9'
services:
  tracker:
    image: tiangolo/uwsgi-nginx-flask:python3.8
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3002:3002"
    environment:
      FLASK_APP: app.py
      # FLASK_ENV: development
      # FLASK_DEBUG:
    # command: sh -c "pip install -r requirements.txt && flask --app index.py --debug run --host=0.0.0.0 --port=3002"
    # command: sh -c "pip install --upgrade pip && pip install -r requirements.txt && flask run --host=0.0.0.0 --port=3002"
    # command: sh -c "pip install --upgrade pip && pip install torch && pip show torch"
    command: sh -c "apt-get update && apt-get install -y --no-install-recommends libglib2.0-0 && apt-get install -y --no-install-recommends libgl1-mesa-glx && rm -rf /var/lib/apt/lists/* && pip install --upgrade pip && pip install -r requirements.txt && flask run --host=0.0.0.0 --port=3002"
    networks:
      - cn332
networks: 
  cn332:
    external: true