version: '3'
services:
  web:
    image: rwightman/pytorch-opencv
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3002:3002"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    # command: sh -c "pip install -r requirements.txt && flask --app index.py --debug run --host=0.0.0.0 --port=3002"
    command: sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0 --port=3002"
